# Generated by Django 2.2.5 on 2019-12-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='libro',
            field=models.ManyToManyField(to='inicio.Libros'),
        ),
    ]
